### ISSUE TITLE
Fingerprint data

### ISSUE THREAD

**Issue by BrillZhang** [hulop/BLELocalization#1]
I'm interesting in this project and I want to use this library in the real world, but how can I get the data of model.json and trainDataSample.json

**Comment by dsato80** [comment]
@BrillZhang sorry for late response, trainDataSample.json is (beacon rssi, location) pair data.
you can collect with [tool](https://github.com/hulop/BeaconSampler2D). 

As for the model.json, it is used in [ModelBuilder](https://github.com/hulop/BLELocalization/blob/master/location-service-library/src/hulo/localization/models/ModelBuilderCore.java)
